name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: runners-privilegedescalation
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'
